# Generated by Django 5.1.1 on 2024-10-06 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submissions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "rar"]
                    )
                ],
            ),
        ),
    ]
