# Generated by Django 5.1.1 on 2024-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorcourse",
            name="role",
            field=models.CharField(
                choices=[("TE", "Teacher"), ("AS", "Assistant"), ("CO", "Coordinator")],
                max_length=15,
            ),
        ),
    ]
