# Generated by Django 5.1.2 on 2024-10-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_atendee_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_id',
        ),
    ]
