# Generated by Django 5.1.1 on 2024-09-25 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_student_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                through="courses.InstructorCourse", to="courses.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="instructorcourse",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.teacher"
            ),
        ),
    ]
